services:
  - type: web
    plan: starter
    name: dall-e-3-discord-bot
    repo: https://github.com/SMccarrick/dall-e-discord-bot
    docker:
      image: oven/bun
    env:
      - group: Dall-E 3 discord bot
    autoDeploy: false
